from typing import List, TypedDict,Optional
from langchain_core.messages import BaseMessage

class GraphState(TypedDict):
    """
    Represents the state of the Gökcen Tarım AI Agent graph.

    Attributes:
        messages: Conversation history (list of Human/AI messages).
        question: The user's original question.
        documents: List of retrieved documents from ChromaDB (context).
        generation: The final response generated by the LLM.
        web_search: Binary flag to indicate if a web search (Tavily) is needed.
        route: The decision made by the Router (e.g., 'vectorstore', 'web_search').
        tool_output: Raw data returned from external tools (Airtable, etc.).
    """
    messages: List[BaseMessage]
    question: str
    documents: List[str]
    generation: str
    web_search: bool
    route: str
    tool_output: str

    product_name: Optional[str]
    customer_info: Optional[dict]